"use strict";
/**
 * OracleModule — Switchboard price feed integration for SSS non-USD stablecoins.
 *
 * ## Architecture
 *
 * ```
 * Switchboard On-Demand Feed (off-chain)
 *        │
 *        ▼
 * Keeper service (this SDK) ──► sss-oracle program ──► OracleConfig PDA
 *                                      │
 *                                      ▼
 *                              MintQuoteEvent / RedeemQuoteEvent
 * ```
 *
 * ## Supported currency pairs (devnet)
 *
 * Fetch live feed addresses from: https://ondemand.switchboard.xyz/solana/devnet
 *
 * | Currency | Pair    | Notes                              |
 * |----------|---------|------------------------------------|
 * | EUR      | EUR/USD | Major FX pair                      |
 * | BRL      | BRL/USD | Brazilian Real                     |
 * | JPY      | JPY/USD | Japanese Yen (small price, ~0.007) |
 * | GBP      | GBP/USD | British Pound                      |
 *
 * ## Quick start
 *
 * ```ts
 * // Initialize an oracle for a EUR-pegged stablecoin
 * const oracle = new OracleModule(provider, mintAddress);
 * await oracle.initialize({
 *   currency: "EUR",
 *   switchboardFeed: SWITCHBOARD_FEEDS["EUR"],
 *   tokenDecimals: 6,
 *   initialPrice: 1_080_000, // 1.08 USD/EUR bootstrap price
 * });
 *
 * // Keeper loop — post Switchboard prices every 30s
 * await oracle.postSwitchboardPrice(feedPrice, feedConfidence, feedTimestamp);
 *
 * // Quote how many EUR tokens to mint for $100 USD
 * const quote = await oracle.getMintQuote(100_000_000); // 100 USD in micro-USD
 * console.log(`Mint ${quote.tokenAmount} EUR tokens`);
 * ```
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.KeeperService = exports.OracleModule = exports.SWITCHBOARD_FEEDS = exports.SSS_ORACLE_PROGRAM_ID = void 0;
const web3_js_1 = require("@solana/web3.js");
const anchor_1 = require("@coral-xyz/anchor");
// ─── Program ID ──────────────────────────────────────────────────────────────
/** SSS Oracle program ID. */
exports.SSS_ORACLE_PROGRAM_ID = new web3_js_1.PublicKey("hntKYM3tbdSnAzYaSU1FvDpFoE8wwBRvY3hpsMHhrN6");
// ─── Known Switchboard On-Demand Feed Addresses ───────────────────────────────
//
// Source: https://ondemand.switchboard.xyz/solana/devnet
// Update these whenever Switchboard rotates feed addresses.
exports.SWITCHBOARD_FEEDS = {
    EUR: new web3_js_1.PublicKey("FNNvb1AFDnDVPkocEri8mWbJ1952HQZtFLuwPiUjSJQ"), // EUR/USD devnet
    BRL: new web3_js_1.PublicKey("5pDCXGRqnbovFnMzBBjf1QMAA1DgYMzBGBuFMbWBWHxV"), // BRL/USD devnet
    JPY: new web3_js_1.PublicKey("2B5d8qFGCriMxvKUYNcLKFEXBtjJfGRvzrXNBvKmFEj2"), // JPY/USD devnet
    GBP: new web3_js_1.PublicKey("CcMtxRVYLByW6STHxLFr13GbqPbpyqPMoiBqRcSyavKe"), // GBP/USD devnet
    // Add CPI, commodity, and custom pegs below:
    // CPI: new PublicKey("..."), // CPI index (slow-moving, staleness 3600s)
};
// ─── Minimal IDL for the oracle program ──────────────────────────────────────
// Full IDL is generated by `anchor build` → `target/idl/sss_oracle.json`
const SSS_ORACLE_IDL = {
    version: "0.1.0",
    name: "sss_oracle",
    instructions: [
        {
            name: "initializeOracle",
            accounts: [
                { name: "authority", isMut: true, isSigner: true },
                { name: "stablecoinMint", isMut: false, isSigner: false },
                { name: "oracleConfig", isMut: true, isSigner: false },
                { name: "systemProgram", isMut: false, isSigner: false },
            ],
            args: [
                {
                    name: "params",
                    type: {
                        defined: "InitOracleParams",
                    },
                },
            ],
        },
        {
            name: "updatePrice",
            accounts: [
                { name: "authority", isMut: false, isSigner: true },
                { name: "oracleConfig", isMut: true, isSigner: false },
            ],
            args: [
                { name: "price", type: "i64" },
                { name: "confidence", type: "u64" },
                { name: "timestamp", type: "i64" },
            ],
        },
        {
            name: "mintQuote",
            accounts: [{ name: "oracleConfig", isMut: true, isSigner: false }],
            args: [{ name: "usdInput", type: "u64" }],
        },
        {
            name: "redeemQuote",
            accounts: [{ name: "oracleConfig", isMut: true, isSigner: false }],
            args: [{ name: "tokenAmount", type: "u64" }],
        },
    ],
    accounts: [
        {
            name: "OracleConfig",
            type: {
                kind: "struct",
                fields: [
                    { name: "authority", type: "publicKey" },
                    { name: "stablecoinMint", type: "publicKey" },
                    { name: "switchboardFeed", type: "publicKey" },
                    { name: "currencyCode", type: { array: ["u8", 8] } },
                    { name: "priceUsd", type: "i64" },
                    { name: "confidence", type: "u64" },
                    { name: "lastUpdate", type: "i64" },
                    { name: "maxStaleness", type: "i64" },
                    { name: "priceLowerBound", type: "i64" },
                    { name: "priceUpperBound", type: "i64" },
                    { name: "maxDeviationBps", type: "u16" },
                    { name: "tokenDecimals", type: "u8" },
                    { name: "bump", type: "u8" },
                    { name: "totalMinted", type: "u128" },
                    { name: "totalRedeemed", type: "u128" },
                ],
            },
        },
    ],
    events: [
        {
            name: "PriceUpdatedEvent",
            fields: [
                { name: "oracle", type: "publicKey", index: false },
                { name: "stablecoinMint", type: "publicKey", index: false },
                { name: "currencyCode", type: { array: ["u8", 8] }, index: false },
                { name: "priceUsd", type: "i64", index: false },
                { name: "confidence", type: "u64", index: false },
                { name: "timestamp", type: "i64", index: false },
            ],
        },
        {
            name: "MintQuoteEvent",
            fields: [
                { name: "oracle", type: "publicKey", index: false },
                { name: "usdInput", type: "u64", index: false },
                { name: "tokenAmount", type: "u64", index: false },
                { name: "priceUsed", type: "i64", index: false },
                { name: "expiresAt", type: "i64", index: false },
            ],
        },
        {
            name: "RedeemQuoteEvent",
            fields: [
                { name: "oracle", type: "publicKey", index: false },
                { name: "tokenAmount", type: "u64", index: false },
                { name: "usdOutput", type: "u64", index: false },
                { name: "priceUsed", type: "i64", index: false },
                { name: "expiresAt", type: "i64", index: false },
            ],
        },
    ],
    errors: [],
};
// ─── OracleModule ─────────────────────────────────────────────────────────────
class OracleModule {
    constructor(provider, mintAddress, programId = exports.SSS_ORACLE_PROGRAM_ID) {
        this.provider = provider;
        this.mintAddress = mintAddress;
        this.programId = programId;
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        this.program = new anchor_1.Program(SSS_ORACLE_IDL, provider);
        this.eventParser = new anchor_1.EventParser(programId, this.program.coder);
    }
    // ─── PDAs ────────────────────────────────────────────────────────
    getOracleConfigPda() {
        return web3_js_1.PublicKey.findProgramAddressSync([Buffer.from("oracle_cfg"), this.mintAddress.toBuffer()], this.programId);
    }
    // ─── Initialize ──────────────────────────────────────────────────
    /**
     * Create an oracle configuration for a stablecoin.
     *
     * @example
     * ```ts
     * const oracleTx = await oracle.initialize({
     *   currency: "EUR",
     *   switchboardFeed: SWITCHBOARD_FEEDS["EUR"],
     *   tokenDecimals: 6,
     *   initialPrice: 1_080_000, // 1.08 USD/EUR
     * });
     * ```
     */
    async initialize(params, authority) {
        const [oracleConfig] = this.getOracleConfigPda();
        const currencyBytes = Buffer.alloc(8);
        currencyBytes.write(params.currency.substring(0, 8), "utf8");
        return this.program.methods
            .initializeOracle({
            currencyCode: Array.from(currencyBytes),
            switchboardFeed: params.switchboardFeed,
            tokenDecimals: params.tokenDecimals,
            maxStaleness: new anchor_1.BN(params.maxStaleness ?? 60),
            priceLowerBound: new anchor_1.BN(params.priceLowerBound ?? 100000),
            priceUpperBound: new anchor_1.BN(params.priceUpperBound ?? 10000000),
            maxDeviationBps: params.maxDeviationBps ?? 500,
            initialPrice: new anchor_1.BN(params.initialPrice),
        })
            .accounts({
            authority: authority.publicKey,
            stablecoinMint: this.mintAddress,
            oracleConfig,
            systemProgram: web3_js_1.SystemProgram.programId,
        })
            .signers([authority])
            .rpc();
    }
    // ─── Update Price (Keeper) ────────────────────────────────────────
    /**
     * Post a verified price from Switchboard to the oracle program.
     *
     * This is called by the keeper service after reading from the Switchboard feed.
     * The on-chain program enforces staleness, bounds, and max deviation.
     *
     * ## Switchboard integration example
     * ```ts
     * // Using @switchboard-xyz/on-demand SDK:
     * import { PullFeed, CrossbarClient } from "@switchboard-xyz/on-demand";
     *
     * const crossbar = new CrossbarClient("https://crossbar.switchboard.xyz");
     * const feed = new PullFeed(connection, SWITCHBOARD_FEEDS["EUR"]);
     * const { value, stdev, slot } = await feed.loadData();
     * const timestamp = await connection.getBlockTime(slot);
     *
     * await oracle.postSwitchboardPrice(
     *   BigInt(Math.round(value * 1_000_000)),  // micro-USD
     *   BigInt(Math.round(stdev * 1_000_000)),  // confidence
     *   timestamp!,
     *   keeperKeypair
     * );
     * ```
     */
    async postSwitchboardPrice(priceUsd, confidence, timestamp, authority) {
        const [oracleConfig] = this.getOracleConfigPda();
        return this.program.methods
            .updatePrice(new anchor_1.BN(priceUsd.toString()), new anchor_1.BN(confidence.toString()), new anchor_1.BN(timestamp))
            .accounts({
            authority: authority.publicKey,
            oracleConfig,
        })
            .signers([authority])
            .rpc();
    }
    // ─── Quotes (simulate) ────────────────────────────────────────────
    /**
     * Get a mint quote: how many tokens to issue for a USD input.
     *
     * Uses `simulateTransaction` — no on-chain state change, no fee.
     *
     * @param usdInput  USD amount in micro-USD (1 USD = 1_000_000)
     * @returns MintQuote with tokenAmount, priceUsed, expiresAt
     *
     * @example
     * ```ts
     * // How many EUR tokens for $100 USD?
     * const quote = await oracle.getMintQuote(100_000_000n);
     * // quote.tokenAmount = 92_592_592 (92.59 EUR @ 6 decimals, EUR/USD=1.08)
     * ```
     */
    async getMintQuote(usdInput) {
        const [oracleConfig] = this.getOracleConfigPda();
        const tx = await this.program.methods
            .mintQuote(new anchor_1.BN(usdInput.toString()))
            .accounts({ oracleConfig })
            .transaction();
        const sim = await this.provider.connection.simulateTransaction(await this._prepareSimTx(tx));
        for (const event of this.eventParser.parseLogs(sim.value.logs ?? [])) {
            if (event.name === "MintQuoteEvent") {
                const d = event.data;
                return {
                    usdInput,
                    tokenAmount: BigInt(d.tokenAmount.toString()),
                    priceUsed: BigInt(d.priceUsed.toString()),
                    expiresAt: Number(d.expiresAt.toString()),
                };
            }
        }
        throw new Error("MintQuoteEvent not found in simulation logs");
    }
    /**
     * Get a redeem quote: how much USD you receive for a token amount.
     *
     * Uses `simulateTransaction` — no on-chain state change, no fee.
     *
     * @param tokenAmount  Token amount in base units (e.g. 1_000_000 = 1 token @ 6 decimals)
     * @returns RedeemQuote with usdOutput, priceUsed, expiresAt
     */
    async getRedeemQuote(tokenAmount) {
        const [oracleConfig] = this.getOracleConfigPda();
        const tx = await this.program.methods
            .redeemQuote(new anchor_1.BN(tokenAmount.toString()))
            .accounts({ oracleConfig })
            .transaction();
        const sim = await this.provider.connection.simulateTransaction(await this._prepareSimTx(tx));
        for (const event of this.eventParser.parseLogs(sim.value.logs ?? [])) {
            if (event.name === "RedeemQuoteEvent") {
                const d = event.data;
                return {
                    tokenAmount,
                    usdOutput: BigInt(d.usdOutput.toString()),
                    priceUsed: BigInt(d.priceUsed.toString()),
                    expiresAt: Number(d.expiresAt.toString()),
                };
            }
        }
        throw new Error("RedeemQuoteEvent not found in simulation logs");
    }
    // ─── State Reader ─────────────────────────────────────────────────
    /** Fetch the current on-chain oracle state. */
    async getConfig() {
        const [oracleConfig] = this.getOracleConfigPda();
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const raw = await this.program.account.oracleConfig.fetch(oracleConfig);
        const now = Math.floor(Date.now() / 1000);
        const lastUpdate = Number(raw.lastUpdate.toString());
        const maxStaleness = Number(raw.maxStaleness.toString());
        return {
            authority: raw.authority,
            stablecoinMint: raw.stablecoinMint,
            switchboardFeed: raw.switchboardFeed,
            currencyCode: Buffer.from(raw.currencyCode)
                .toString("utf8")
                .replace(/\0/g, ""),
            priceUsd: BigInt(raw.priceUsd.toString()),
            confidence: BigInt(raw.confidence.toString()),
            lastUpdate,
            maxStaleness,
            priceLowerBound: BigInt(raw.priceLowerBound.toString()),
            priceUpperBound: BigInt(raw.priceUpperBound.toString()),
            maxDeviationBps: raw.maxDeviationBps,
            tokenDecimals: raw.tokenDecimals,
            totalMinted: BigInt(raw.totalMinted.toString()),
            totalRedeemed: BigInt(raw.totalRedeemed.toString()),
            isPriceFresh: now - lastUpdate <= maxStaleness,
        };
    }
    /** Human-readable price as a decimal string. Example: "1.08" for EUR/USD = 1_080_000. */
    static formatPrice(microUsd) {
        const whole = microUsd / 1000000n;
        const frac = microUsd % 1000000n;
        return `${whole}.${frac.toString().padStart(6, "0")}`;
    }
    // ─── Internal ─────────────────────────────────────────────────────
    async _prepareSimTx(tx) {
        const { blockhash } = await this.provider.connection.getLatestBlockhash("confirmed");
        tx.recentBlockhash = blockhash;
        tx.feePayer = this.provider.wallet.publicKey;
        return tx;
    }
}
exports.OracleModule = OracleModule;
// ─── Keeper Service ───────────────────────────────────────────────────────────
/**
 * KeeperService — polls a Switchboard feed and pushes price updates.
 *
 * ## Usage
 * ```ts
 * const keeper = new KeeperService(oracle, keeperKeypair, {
 *   intervalMs: 30_000,     // poll every 30s
 *   feedUrl: "https://crossbar.switchboard.xyz",
 * });
 * await keeper.start();
 * // ... runs until keeper.stop()
 * ```
 *
 * In production, run this as a Docker service:
 *   `docker compose up sss-oracle-keeper`
 */
class KeeperService {
    constructor(oracle, keeperKeypair, opts = {}) {
        this.oracle = oracle;
        this.keeperKeypair = keeperKeypair;
        this.opts = opts;
        this.running = false;
    }
    /**
     * Start the keeper polling loop.
     *
     * Requires a `fetchSwitchboardPrice` implementation — see `fromSwitchboard()`.
     */
    async start(fetchPrice) {
        if (this.running)
            return;
        this.running = true;
        const tick = async () => {
            if (!this.running)
                return;
            try {
                const { priceUsd, confidence, timestamp } = await fetchPrice();
                await this.oracle.postSwitchboardPrice(priceUsd, confidence, timestamp, this.keeperKeypair);
                this.opts.onUpdate?.(priceUsd, timestamp);
            }
            catch (err) {
                (this.opts.onError ?? console.error)(err);
            }
            if (this.running) {
                this.timer = setTimeout(tick, this.opts.intervalMs ?? 30000);
            }
        };
        await tick();
    }
    stop() {
        this.running = false;
        if (this.timer)
            clearTimeout(this.timer);
    }
}
exports.KeeperService = KeeperService;
